# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='edits',
        ),
    ]
